#!/usr/bin/env bash
# This script configures a server to listen on port 80 of all the server’s active

sudo sed -i "s/ipv6only=on//" /etc/nginx/sites-available/default
sudo rm -f /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
