#!/usr/bin/env bash
# Let’s install the ufw firewall and setup a few rules on web-01
# We configure ufw so that it blocks all incoming traffic, except:
# 22 (SSH), 443 (HTTPS SSL), 80 (HTTP)

sudo apt install ufw
sudo ufw status
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp 
sudo ufw enable
sudo ufw status verbose
# sudo ufw reload
